import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import ShowNavigation from "@/components/layouts/navigation/ShowNavigation";
import ReactQueryProvider from "@/providers/ReactQueryProvider";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`  ${inter.className}  antialiased bg-background-secondary`}
      >
        <ReactQueryProvider>
          {/* Navigation এখন শর্ত অনুযায়ী show/hide হবে */}
          <ShowNavigation />

          {children}
        </ReactQueryProvider>
      </body>
    </html>
  );
}
